// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrayerTrackerWebAPI.Models;

#nullable disable

namespace PrayerTrackerWebAPI.Migrations
{
    [DbContext(typeof(PrayerDbContext))]
    [Migration("20251223035220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.AdminLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__AdminLog__5E5499A8D21362FE");

                    b.HasIndex("AdminId");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.Prayer", b =>
                {
                    b.Property<int>("PrayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrayerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.HasKey("PrayerId")
                        .HasName("PK__Prayers__72701224125A8A6E");

                    b.ToTable("Prayers");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.PrayerGuidance", b =>
                {
                    b.Property<int>("GuidanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GuidanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GuidanceId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("VideoURL");

                    b.HasKey("GuidanceId")
                        .HasName("PK__PrayerGu__FBED6C864E91624E");

                    b.ToTable("PrayerGuidance", (string)null);
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.PrayerRecord", b =>
                {
                    b.Property<int>("PrayerRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrayerRecordID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrayerRecordId"));

                    b.Property<int>("PrayerId")
                        .HasColumnType("int")
                        .HasColumnName("PrayerID");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("PrayerRecordId")
                        .HasName("PK__PrayerRe__6E62241E79F52DA3");

                    b.HasIndex("PrayerId");

                    b.HasIndex("UserId");

                    b.ToTable("PrayerRecords");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC0F5A594D");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534FD90AD31")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.AdminLog", b =>
                {
                    b.HasOne("PrayerTrackerWebAPI.Models.User", "Admin")
                        .WithMany("AdminLogs")
                        .HasForeignKey("AdminId")
                        .IsRequired()
                        .HasConstraintName("FK__AdminLogs__Admin__31EC6D26");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.PrayerRecord", b =>
                {
                    b.HasOne("PrayerTrackerWebAPI.Models.Prayer", "Prayer")
                        .WithMany("PrayerRecords")
                        .HasForeignKey("PrayerId")
                        .IsRequired()
                        .HasConstraintName("FK__PrayerRec__Praye__32E0915F");

                    b.HasOne("PrayerTrackerWebAPI.Models.User", "User")
                        .WithMany("PrayerRecords")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PrayerRec__UserI__33D4B598");

                    b.Navigation("Prayer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.Prayer", b =>
                {
                    b.Navigation("PrayerRecords");
                });

            modelBuilder.Entity("PrayerTrackerWebAPI.Models.User", b =>
                {
                    b.Navigation("AdminLogs");

                    b.Navigation("PrayerRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
